apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PiXqCQWARcslKidNgo1kaA==,iv:fQSixwH6xnwUlNZaKi1Rs/6vN+toQygthkQhghRNt+I=,tag:qd7iIib3io1ukt0Cw7Ysjg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ZwThodPT9TSU7HIujoSi9A4qwciBii0O5g9FVYZK31Bm1C+27w==,iv:t8fnlaLaVi99R4Xx3yGSCawPeUYOrzcGbr+cZiIWEKU=,tag:bp9W05SM59LN+/lkHeS6DQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:F1efzN82qgQ0MB5KHl+F,iv:tDMgvRJI97PhXCd7FsFER+WeGJYUe6+/ffol7UoAOMQ=,tag:Q3b5iAyaVC5eIkuhfgzDAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK3R4bGhsZUxVSmNwdnhW
            MEpQWHF2bkw2d3hwS2VTZGM3dHR2TXJxcVQwCmNrUkxWa3lXNDJRb213RFF3OUZn
            QVZaMHZvYnNna3M1bDQwSUpjSnZ5dFkKLS0tIGtkdUNtaTUvNllFd0VuQ2NWTXlT
            Q2dFeS9OM3o3WjZSL3A5QVltb3o3ancKuDX6QuU9su/cxCsGNDvc+BRXhR2rfg+U
            1j8YppbmSK4JED+cS7y5tKZ+3KpsqpUFzDpf/qgGDP9pXRvaAaAYKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T02:23:48Z"
    mac: ENC[AES256_GCM,data:2zJyurLHrqCY67QwV2e2HAgfZKOnyH2LHebpM5r2cOIyn1cCI0Q5wTttNft1bofN4nasY6XDASbTS/mJBSwU6S2FYG5CJwLldm5vdFGwuOtdHOiITQx9TyKqSS3MfrzTnSzltinRCtcWYE75whe9JbrB1zL/saTu2Lp7prV2IXo=,iv:qYLfwj1LGUdkRl3Iz/qfy9A9XopNSedNOCgOBkdb3kc=,tag:WvRlXXVwsvimNbB38gkF5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
