---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.1.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs-charts
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
