---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./uptime-kuma/ks.yaml
  - ./cloudnative-pg/ks.yaml
  - ./redis/ks.yaml
  - ./dashy/ks.yaml
  - ./whoogle/ks.yaml
