apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:hliz,iv:Gkudq7yqbj2iSEZKBuJz0hnknfMau4eeNUchHc2tum8=,tag:5TGsWoHQkzbGND05HgIwFQ==,type:str]
    password: ENC[AES256_GCM,data:ZeHE3XBQUzTSERrodZE=,iv:j9I3bU0RJzNfBx0fgoX80lyF56bvT8gIqHNrwConhEw=,tag:+36Sa+nKNzm3hHacP/EePg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbzdYUmtSdm1RdEU3ajJp
            aXFJNEV3TWI2RHVtYmNNd0lYNUkzQlBRcml3Cm5JTEw0SHJPY2R3UWhRbDB6QzUr
            VS9aNjl1S2NCSW00UXhRRW1BcjRzWDAKLS0tIDY5NXhidHBsdDFXSnp3N0s1MUhj
            TkxxakhMNTdJRlI0amRuWlY5RzlSU0EKUgIEWsdEYq0VmWBpDvDL78EIlqcMOZQm
            trM4z2brHdvwCKhtwib3kdF1M5yvcf871hQlePlUvmBeV5hj0dLi7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T20:28:22Z"
    mac: ENC[AES256_GCM,data:/Nr/9bErR1WWn7WC0K9OCqmVFvGtGYZtTSpzvDrIu/pPigDkREZLQy4HzOleBnx32NJrakh3RRc5cOnZuUSU1YWxUyIS1FDm5fURz6i4Nsl1j+sM10GPd0rDIUQtPHaLn9S1gFMexN/YV6ZTMQqSwYo2pz183bPNaB8xLggbpOg=,iv:mcyyQipuoWXD3rvBeZAAl5zaDgx6Dog28sg1y2//cDI=,tag:cAQbC509cktVLGsKWY+k7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
