apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:p+SNJ0iYv1q14A==,iv:zwD1ENePtHULVKPAvodSpdD6gtVeOYXYDzSQe9a7XdI=,tag:K2+0/hXg4M0Sf3q9PP5i+A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:QHOCTt/KcgJKDMbgEs3mvA==,iv:mkClpiKQdQZ5tisZVibALMBB1tr0acE4TtH6GTJ/zEs=,tag:MPQmMoUOQdumbGq8bPl2rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS0Ixa2VETnBKZ3NSWnht
            eUtWM00yWGpSMk9TYThSU294enc1UVBmMHpRCmJhZ2pCSnpvYXpTc21UMWVYempF
            dmdIWENLU3RJQ2kyeVlLUHBrQUIvbTgKLS0tIDArOTZHVjdrT3NSbXRCb3JHT3Bo
            Z1RLTlp1N2s5SkRkYUFiS0phUTl6c1UKVJmN8dP3S7KeGa9CLrO73k4SlsPUu8to
            Dbz6cAG/acDFPjM7lTdPYfbgobyvpH69R54IWYSV6+/TD7HaxLMk7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T17:51:48Z"
    mac: ENC[AES256_GCM,data:Pd+K+ANG/uS4Q7lb8gsAm/Q8aYmUvydjr0/7jV2hWsBTH0X5p2I+Bwou7nSKjEtg9Tlwubap7eRZrEHC/XvBq0W5teaB+6PqX9TOc84hRd1nVvByVOPxauFLxpNcGN/SipxauBGn/pv7ZKVl/mALchLG4MvZcfqy5ZbCXEYtQD4=,iv:8q/e66kAa5bU/TI1cg+5bj7qqW4yipAAQQGIta8iRmo=,tag:fOy66z4RiMFCL9KeHsUhHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
