apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:0c2Wh+x6NRNcew==,iv:rHL1L8AdACKgmvnDjNfPcces2SZpUKKvtSKg95DYD6A=,tag:ocZwhZvBhlMmO496ihs8bQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TUXk8LPZ7YriOcAlUs8hGg==,iv:jDzqIUSkWxoeF5p0sFAqTZh5nh/4TzD9i66kBqNIp9c=,tag:NPw4KU+a0bDq8EdB1jz/jA==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:h51LBB46gJi80kApq6hTpmkgMeGOAhS2htEnHSTnC4auU82iMzOuVA==,iv:2ROcu/LxYQOIquOjIEB/jnj2lIRgvVrdDymi1Sdo5b4=,tag:9Yeig18Eejij+S6VZPYM1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMm5LY2NIbkNUdWlGMlFH
            RCsyaVc0NWJaZ1ZGaUlBM20wd05pdyt0VFNZCmRlM0RpNmx4SnZJSE1pOStXTVhT
            azV6WGQvYzh1WWQ2Mlk0d2hFZWthUlkKLS0tIG13T21xRmV6T1B1eGJxSHJGVXVk
            WWhwUGRqelNFYytSU2wzeXJTaExUVTQK3bcQEOgmorz78rzicXd+7jUpG8buq+2J
            Ur7/ykWmUSOujVabn7xvmK6d+2qlydDg6XKs8CUtWpqiOfmWaAGFMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T05:25:00Z"
    mac: ENC[AES256_GCM,data:HfXG7z4FKSDCh3DB5SUk+2CULG1dIFhn7Ap1Nsx8EaoXWzeR73Qr4JlSUTixL/iFoagKbSitABAsavRxZNOqQzNm03prGFdGHse8E9OM0BbllDoL/sfSlpXvriSEfEylobflLnurFOUyKx4Xq5zKo2Q2l/UcNezjvHuzJkYS0cc=,iv:xdIGhAByRi83xK+QTHEEgO2737Gx2PjlOgLcpcn54yM=,tag:kgT5iAJU7DPmmeXFdzTV3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
