---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: &name uptime-kuma
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
