# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: home
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:WvJG,iv:eO0YVW+G2/P48qfUPhyu6vFX0CMV3oFcDdh+gS3GOjE=,tag:aadBHGdnsJ7HRVDgHjBsrg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:1jhGCZ+JChAi0fb970M=,iv:lhpsCW1mmsNV5ZLb0w3uh4RCTGO2twXUvr5tMcDihTs=,tag:bvg5F+SliK4WseYHxBYS0g==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:ODrVg5PfyAXkj/o9rw==,iv:K11ITCClQOtVII2lVajJwQm5oUGPGWhZ6j8xtqpzINU=,tag:LZtIqxlBQa3VxD6fMNO0tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age128krajjl3y8e38wzt7cjh35jj7l8j0y780e8xwf6gn883euu0atsxc9knh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMi9nOHh5UXhRREtkREtN
            bnlpVU9uOG1EWHVBaldXWThvZzFheVRQbFY0Cm05LzZiTnhrblpHUGVkb2Y3NUtw
            U3oyclhvR0RVd1lhbDJ5cUtsQmhlTmsKLS0tIGZTWlB0WHoyd09UMmxYTEJ4YW5m
            cm1aTTNiSjRhUmlSMGd4S1NHR1NaQjgKnHT11Uy2z66hJD3f7p4KI4luzj+VoHBc
            q+fgAfvvy0dGns11bhH6y0nL6g7qjWGyVQb6kQrCap0LCYZppEuONg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T21:36:12Z"
    mac: ENC[AES256_GCM,data:tkrTWn2M97fULaSLJOritbR+/kbxwMeAFila2DiM75cmRb9UhIon/uAoBNi+yoiBuvJdc4fN7hdIin5HURjYI65Hhj1hEg4/hGN6myMjCcg+IytPHfOq7iuIZY03hD8KnpKEAelGKHYt4pKDHRNVd3OhDfv83+U3/J8cjs+nAJ4=,iv:tjpoAUlwThHZv3jPLHl5stLgAGRvQIVb2UzIsm/q6ic=,tag:Ja1HHjCjjXrsI2FdDSBz6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
